[project]
name = "text-adventure"
version = "0.1.0"
description = "A text adventure game using Peewee ORM with SQLite"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "peewee>=3.16.0",
]
